//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "___VARIABLE_productName:identifier___ViewController.h"
#import <UIKit/UIKit.h>

@interface ___VARIABLE_productName:identifier___ViewController () <___VARIABLE_productName:identifier___View>

@end

@implementation ___VARIABLE_productName:identifier___ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    [self configureUI];
    [self.presenter viewDidLoad];
}

- (void)configureUI {
    //configure UI
}

@end
