//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "___VARIABLE_productName:identifier___Assembly.h"
#import "___VARIABLE_productName:identifier___ViewController.h"
#import "___VARIABLE_productName:identifier___Presenter.h"
#import "___VARIABLE_productName:identifier___Protocols.h"
#import "___VARIABLE_productName:identifier___Router.h"

@interface ___VARIABLE_productName:identifier___Assembly ()

@end

@implementation ___VARIABLE_productName:identifier___Assembly

+ (UIViewController *)createModule {
    ___VARIABLE_productName:identifier___ViewController *view = [[___VARIABLE_productName:identifier___ViewController alloc] init];
    ___VARIABLE_productName:identifier___Router *router = [[___VARIABLE_productName:identifier___Router alloc] init];
    ___VARIABLE_productName:identifier___Presenter *presenter = [[___VARIABLE_productName:identifier___Presenter alloc] initWithView:view router:router];
    view.presenter = presenter;
    router.viewController = view;
    return view;
}

@end
