//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

//Router implement navigateTo func
@protocol ___VARIABLE_productName:identifier___WireframeInterface <NSObject>

//example
@required - (void)navigateToDismiss;

@end

@protocol ___VARIABLE_productName:identifier___View <NSObject>

@end

@protocol ___VARIABLE_productName:identifier___PresenterInterface <NSObject>

- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)viewWillDissappear;
- (void)viewDidDissappear;

@end


NS_ASSUME_NONNULL_END
