//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "___VARIABLE_productName:identifier___Router.h"
#import "___VARIABLE_productName:identifier___Protocols.h"

@implementation ___VARIABLE_productName:identifier___Router

- (void)navigateToOption:(___VARIABLE_productName:identifier___NavigationOption)option {
    UIViewController *vc;
    switch (option) {
        case dissmis:
            [self.viewController dismissViewControllerAnimated:true completion:nil];
            return;
        case pop:
            if (self.viewController.navigationController){
                [self.viewController.navigationController popViewControllerAnimated:true];
            }
            return;
        case auth:
            break;
    }
    
    if([vc isKindOfClass:[UINavigationController class]]){
        [self.viewController presentViewController:vc animated:true completion:nil];
    } else if ([vc isKindOfClass:[UIViewController class]]) {
        if (self.viewController.navigationController){
            [self.viewController.navigationController presentViewController:vc animated:true completion:nil];
        } else {
            [self.viewController presentViewController:vc animated:true completion:nil];
        }
    }
}

@end
