//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "___VARIABLE_productName:identifier___Presenter.h"
#import "___VARIABLE_productName:identifier___Protocols.h"

@interface ___VARIABLE_productName:identifier___Presenter () <___VARIABLE_productName:identifier___PresenterInterface>
@property (strong, nonatomic) NSObject<___VARIABLE_productName:identifier___WireframeInterface>* router;
@end

@implementation ___VARIABLE_productName:identifier___Presenter

- (instancetype)initWithView:(NSObject<___VARIABLE_productName:identifier___View>*)view router:(NSObject<___VARIABLE_productName:identifier___WireframeInterface>*)router
{
    self = [super init];
    if (self) {
        self.view = view;
        self.router = router;
    }
    return self;
}

- (void)viewDidAppear {
    //Default implementation
}

- (void)viewDidDissappear {
    //Default implementation
}

- (void)viewDidLoad {
    //Default implementation
}

- (void)viewWillAppear {
    //Default implementation
}

- (void)viewWillDissappear {
    //Default implementation
}

@end
