//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <UIKit/UIKit.h>
#import "___VARIABLE_productName:identifier___Protocols.h"

NS_ASSUME_NONNULL_BEGIN

@interface ___VARIABLE_productName:identifier___ViewController : UIViewController<___VARIABLE_productName:identifier___View>

@property (nonatomic, strong) NSObject<___VARIABLE_productName:identifier___PresenterInterface>* presenter;

@end

NS_ASSUME_NONNULL_END
