//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "___VARIABLE_productName:identifier___Protocols.h"

@interface ___VARIABLE_productName:identifier___Presenter: NSObject<___VARIABLE_productName:identifier___PresenterInterface>
@property (nonatomic, weak) NSObject<___VARIABLE_productName:identifier___View> *view;
- (instancetype)initWithView:(NSObject<___VARIABLE_productName:identifier___View>*)view
                      router:(NSObject<___VARIABLE_productName:identifier___WireframeInterface>*)router;
@end


