//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "___VARIABLE_productName:identifier___Router.h"
#import "___VARIABLE_productName:identifier___Protocols.h"

@implementation ___VARIABLE_productName:identifier___Router

- (void)navigateToDismiss { 
    [self.viewController dismissViewControllerAnimated:true completion:nil];
}

- (void)navigateTo:(UIViewController *)vc {
    if([vc isKindOfClass:[UINavigationController class]]){
        [self.viewController presentViewController:vc animated:true completion:nil];
    } else if ([vc isKindOfClass:[UIViewController class]]) {
        if (self.viewController.navigationController){
            [self.viewController.navigationController pushViewController:vc animated:true];
        } else {
            [self.viewController presentViewController:vc animated:true completion:nil];
        }
    }
}

@end
